
# Spring配置
spring:
  application:
    name: wechat-ai-bot
  # 配置日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456 #如果没设置密码就没有密码，设置了才会有
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（适用负值表示没有限制）
        max-wait: -1  #连接池最大阻塞等待时间（适用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  main:
    allow-bean-definition-overriding: true

# 微信机器人配置
wxbot:
  # appid
  appid: Qsjt6WXrNUjZFzO
  # token
  token: riIY6DBhz3efthqvEEMUFqtSsZpeMC
  # encodingAESKey
  encodingAESKey: lJgwtEgNBDIq1ZapoOWj2CDeGsBURG4e9dvKYOJCHSJ

# 服务端口配置
server:
  port: 8081